require("travis.remaps")  -- Has to be before plugins
require("travis.plugins")
require("travis.telescope")
require("travis.colors")
-- require("travis.treesitter")
require("travis.set")
require("travis.comment")
require("travis.lspconfig")
require("travis.octo")
require("travis.epoch_converter")
require("travis.blame")
require("travis.gitlinker")
-- require("travis.oil")
